spring:
  threads:
    virtual:
      enabled: true
  config:
    activate:
      on-profile: development
  datasource:
    hikari:
      username: postgres
      password: password
    url: jdbc:postgresql://localhost:5432/stamp_reporter
  grpc:
    client:
      channels:
        io-balancer:
          address: 0.0.0.0:7331
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml
  task:
    scheduling:
      pool:
        size: 1
application:
  mqtt:
    broker-url: tcp://localhost:1883
    client-id: stamp-reporter-client
    username: username
    password: password
    inbound-topic: topic1
    outbound-topic: topic1
  workers:
    amount: 50
  api-callers:
    stamp-server:
      url: http://localhost:31313
  grpc:
    client:
      channels:
        io-balancer:
          enabled: false
server:
  port: 8882
