spring:
  config:
    activate:
      on-profile: staging, production
  datasource:
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    url: ${DB_JDBC_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  grpc:
    client:
      channels:
        io-balancer:
          address: ${IO_BALANCER_ADDRESS}
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml
  task:
    scheduling:
      pool:
        size: 4
application:
  grpc:
    client:
      channels:
        io-balancer:
          enabled: false
  api-callers:
    stamp-server:
      url: ${STAMP_SERVER_URL}
